### ISSUE TITLE
How do I install the module via composer?

### ISSUE THREAD

**Issue by cerebrumgit** [magefan/module-login-as-customer#1]
Hello good afternoon

How do I install the [module](https://magefan.com/login-as-customer-magento-2-extension) via composer?

**Comment by magefan** [comment]
Hello Cerebrumgit.

Currently we do not provide installation instruction via composer.

But you can just:
1. Download extension archive
2. Extract files
3. Upload app folder over ftp to you magento 2 root directory
4. Variant A: Then install extension by running command in magento 2 directory using shell
 php bin/magento setup:upgrade
4.Variant B: Then install extension using Magento 2 Component Manager
(Admin Panel > System > Web Setup Wizard > Component Manager)

Best Regards
Ihor

**Comment by cerebrumgit** [comment]
ok, thank you for information
