### ISSUE TITLE
how to save admin info to order level?

### ISSUE THREAD

**Issue by sivajik34** [magefan/module-login-as-customer#11]
1.Magefan\LoginAsCustomer\Controller\Adminhtml\Login\Login 

        $userName=$user->getUsername();
        $encodedUserName=strtr(base64_encode($userName), '+/=', '._-');

        $redirectUrl = $url->getUrl('loginascustomer/login/index', ['secret' => $login->getSecret(), '_nosid' => true,'csr'=>$encodedUserName]);

2.Magefan\LoginAsCustomer\Controller\Login\Index
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $catalogSession = $objectManager->get('\Magento\Catalog\Model\Session');
        $csr = $this->getRequest()->getParam('csr');
                  
            if($csr!='' && $csr!=null){               
              $userName=base64_decode(strtr($csr, '._-', '+/='));
              $catalogSession->setCsrValue($userName);
                }
        $this->messageManager->addSuccess(
            __('You are logged in as customer: %1', $login->getCustomer()->getName())
        );

        $this->_redirect('*/*/proceed');

public function execute(EventObserver $observer)
    {
        $order = $observer->getOrder();
        $csrValue=$this->catalogSession->getCsrValue();
        if($csrValue!='' && $csrValue!=null){
        $order->setCsrname($csrValue);
        }       
        return $this;
    }

<event name="sales_model_service_quote_submit_before">
        <observer name="csrsave" instance="Dcw\Search\Observer\CsrSave"/>
    </event>

But its not working. Do you have any idea? can you help me on this.

**Comment by sivajik34** [comment]
we want to save customer service Rep name in order level in admin.
So I'm passing extra param (username ) to url , then I'm trying to save catalog session.
in order place event we want to save the value.
session is not working.

**Comment by francosabolo** [comment]
Hi ! I could make this work by sending username to authenticateCustomer function like this in Magefan\LoginAsCustomer\Controller\Login\Index 
$admin_user = $this->getRequest()->getParam('csr');
$login->authenticateCustomer($admin_user);

Then, inside the function I set a customer session with the admin user name : 
$this->_customerSession->setData('admin_username',$adminuserName);

Finally, i can retrieve the admin_username from customer session anywhere like this: 

$this->_customerSession->getData('admin_username');    

Hope it helps ! @sivajik34
