### ISSUE TITLE
Duplicate Active Quotes

### ISSUE THREAD

**Issue by lewisvoncken** [magefan/module-login-as-customer#18]
When you use the login as customer functionality for an existing customer which already has a filled quote then a new quote will be create. 

Because of this situation it is possible that a customer has multiple active quotes and when the customer submits the new quote and places an order the original quote will be activated. Now the customer has random old products in his shopping cart form his own original quote

See the screenshot of the quote table with 3 active quotes

![image](https://user-images.githubusercontent.com/6040343/38860622-e86dbe8e-4230-11e8-9106-db32a3711be2.png)

**Comment by magefan** [comment]
Hello @lewisvoncken , what Magento and log in as customer extension versions do you use?

**Comment by lewisvoncken** [comment]
@magefan I have installed the latest version with in a Magento 2.1.4 and a Magento 2.1.12 installation and in both situations the problem exists

Below you can find a query to find all duplicate active quotes within the same website:

```
/** Check for duplicate active quotes within the same website */
SELECT `entity_id`, `quote`.`store_id`, `quote`.`is_active`, `customer_id`, `customer_email`, `store`.`website_id`, COUNT(*) counter 
FROM `quote`
INNER JOIN `store` ON `store`.`store_id` = `quote`.`store_id`
WHERE `customer_id` IS NOT NULL 
AND `quote`.`is_active` = 1 
GROUP BY `customer_email`,  `store`.`website_id`
HAVING COUNT(*) > 1 
ORDER BY `counter`  DESC
```
