### ISSUE TITLE
Does not work for Login Restricted Websites

### ISSUE THREAD

**Issue by Sam-PUMP** [magefan/module-login-as-customer#2]
# Fails When Access Restriction Login is active
In Configuration, when  **_General > Website Restrictions > Restriction Type_**  is set to > **Login**
User can't login as customer, and is stuck on front-end Account Login Page

It would be great if Login as customer could also bypass this initial restriction by logging in and authenticating as customer at this entry point also. 

# Work Around
To work around the issue you need to first login manually on the front-end with any user that meets the access allowed criteria in admin (you can create one or use your own login).  Then once logged in, go back to admin and click **Login as customer**.  This isn't ideal because the sessions get mixed with the user used to bypass login restrictions. 

How come module can't login as customer when login restrictions are on? Can it not authenticate prior to this block or restriction?

thanks

**Comment by magefan** [comment]
@Sam-PUMP  I think you are using some third-party [extension](https://magefan.com/login-as-customer-magento-2-extension) on you Magento 2, because I cannot find any "Website Restrictions" area in Stores > Configurations (Magento CE 2.1)

Please let me know if I'm right or not.

**Comment by Sam-PUMP** [comment]
Hi no its not a 3rd party extension but a feature of I guess enterprise. Sorry I was not aware that feature was not in community. Would you consider doing an enterprise version? It's still basically the same feature - > bypass customer login

Thanks !

**Comment by magefan** [comment]
@Sam-PUMP please try fix https://github.com/magefan/module-login-as-customer/commit/4b9b5a50d2d535a62b70deeaeec793b6987c6665

Don't forget to flush Magento cache. Let me know if this works for you.

**Comment by magefan** [comment]
@Sam-PUMP any news?

**Comment by Sam-PUMP** [comment]
Hi! Yes it works on entreprise !Sorry for the delay I only got a chance to install it recently. But thank you so much for such a quick solution and turn around! :)
