### ISSUE TITLE
Secret Key Invalid

### ISSUE THREAD

**Issue by darshan-khatri-16** [magefan/module-login-as-customer#20]
Hi There,
We are using your extension for one of our client. When we frequent users are click on "Login as Customer", it redirects to dashboard. Basically default magento's secret key got invalid.
Could you please check this on priority basis and give me update on it?

Thanks,
Darshan Khatri

**Comment by magefan** [comment]
Hello @darshan-khatri-16 , "magento's secret key got invalid." when you stay on some admin page too long and then press any of the links in the admin panel, so I don't this that this can be fixed in our module.

**Comment by darshan-khatri-16** [comment]
Hi There,
This is not the case. When I tried hitting "Login As Customer" multiple times token got expired, this is not the issue of the secret key is getting expired because of page waiting for too long for sure.
Thanks,
Darshan Khatri

**Comment by magefan** [comment]
@darshan-khatri-16 , wat magento version, and extension version do you use?

**Comment by darshan-khatri-16** [comment]
Hi There,
We are using Magento enterprise edition version 2.1.9 and extension version 2.1.1 (i.e specified in module.xml).
If possible can we set up a call so that I can show you on call?

Thanks,
Darshan Khatri
