### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by erfanimani** [magefan/module-login-as-customer#21]
Not necessarily an issue, but it would be great if we could include a changelog section inside the `readme.md` file :)

**Comment by magefan** [comment]
Done. https://github.com/magefan/module-login-as-customer/commit/a929c00c2aba53c9372df4b01ff6ee089deeddd6

We have included link to our website where you can find chnage log tab. We cannot include the changelog text into readme beckouse of SEO issues.

**Comment by erfanimani** [comment]
Thanks!
