### ISSUE TITLE
404 error after logging as customer on customer grid

### ISSUE THREAD

**Issue by PiroozMB** [magefan/module-login-as-customer#23]
Hi
I have a magento2.2.3 installed [Magento 2 Login As Customer](https://magefan.com/login-as-customer-magento-2-extension) for many customers when I login it gets opened in a new page and gives a 404 error. for some customers it works fine but for most of them not. This issue is for customer group "personnel"

**Comment by magefan** [comment]
@PiroozMB , could you please confirm that you use Login as Customer extension v2.1.7?

**Comment by PiroozMB** [comment]
@magefan  
I confirm that i have extension v 2.1.7 installed and even if it logs in, it won't show the special prices for that user even after clearing the static files and cache and rebuilding them. Because the session is not set correctly and it says : invalid secret key after logging in.

**Comment by magefan** [comment]
@PiroozMB , this can be related to the customer data. The customer store_id is 0.
We will make a fix for this issue in next releases.

**Comment by magefan** [comment]
This was fixed in extension v2.1.7 
https://magefan.com/login-as-customer-magento-2-extension/change-log
