### ISSUE TITLE
Special prices from catalog price rule not showing after logging in as customer 

### ISSUE THREAD

**Issue by PiroozMB** [magefan/module-login-as-customer#24]
Magento 2.2.3 . Customer group is not recognized so the special prices for that customer won't show .

**Comment by magefan** [comment]
@PiroozMB , could you please confirm that you use Login as Customer extension v2.1.7?

**Comment by magefan** [comment]
Working on this issue

**Comment by magefan** [comment]
We were not able to reproduce this issue on the latest [Magento 2 Login as customer](https://magefan.com/login-as-customer-magento-2-extension) extension version v2.2.1
