### ISSUE TITLE
2.1.5 is installed via composer, shouldn't be 2.1.8?

### ISSUE THREAD

**Issue by oviliz** [magefan/module-login-as-customer#25]
> $ composer require magefan/module-login-as-customer
> Using version ^2.1 for magefan/module-login-as-customer
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Package operations: 2 installs, 0 updates, 0 removals
>   - Installing magefan/module-community (2.0.2): Loading from cache
>   - Installing magefan/module-login-as-customer (2.1.5): Downloading (100%)         
> Package sjparkinson/static-review is abandoned, you should avoid using it. Use phpro/grumphp instead.
> Writing lock file
> Generating autoload files

2.1.5 vs 2.1.8 https://github.com/magefan/module-login-as-customer/releases

**Comment by magefan** [comment]
@oviliz , you get 2.1.5 as you have added Login As Customer to your account at magento marketplace, and there the latest version of this extension is still 2.1.5 (https://marketplace.magento.com/magefan-module-login-as-customer.html). Use this command to get v2.1.8

`composer require magefan/module-login-as-customer ^2.1.8`

For the changelog, you can visit our website
https://magefan.com/login-as-customer-magento-2-extension
