### ISSUE TITLE
Installing via Composer would install the old 2.1.5

### ISSUE THREAD

**Issue by oviliz** [magefan/module-login-as-customer#26]
Hi guys, the module hasn't been updated at https://marketplace.magento.com/magefan-module-login-as-customer.html so it would install the old version.

**Comment by magefan** [comment]
To install the latest version of [Magento Login As Customer](https://magefan.com/login-as-customer-magento-2-extension) extension please run CLI command

`composer require magefan/module-login-as-customer ^x.x.x`

**x.x.x** - is a version you want to install.
