### ISSUE TITLE
recommended to update the extension to the newest version 2.1.7

### ISSUE THREAD

**Issue by jaashy89** [magefan/module-login-as-customer#27]
even after installing 2.1.7 version i am getting message -
Attention! You use an old version of [Magento 2 Login As Customer Extension](https://magefan.com/login-as-customer-magento-2-extension). It is strongly recommended to update the extension to the newest version 2.1.7 which contains a critical fix for the customer quote (shopping cart).
Read Details

**Comment by magefan** [comment]
@jaashy89 , please check this article 
https://magefan.com/blog/manage-magento-2-admin-notifications/
