### ISSUE TITLE
Does not work with Magento 2.3.2

### ISSUE THREAD

**Issue by namchinhh** [magefan/module-login-as-customer#30]
I success to install the module but cannot complete the di:compile command. 
I can see that the construct of class Magefan\LoginAsCustomer\Model\AdminNotificationFeed is wrong cause the construct of parent class \Magento\AdminNotification\Model\Feed has updated in 2.3.2

bin/magento setup:di:compile
Compilation was started.
Interception cache generation... 6/7 [========================>---]  85% 1 min 478.0 MiBErrors during compilation:
        Magefan\Community\Model\AdminNotificationFeed
                Incompatible argument type: Required type: \Magento\Framework\Module\Manager. Actual type: \Magento\Framework\Model\ResourceModel\AbstractResource; File: 
/src/vendor/magefan/module-community/Model/AdminNotificationFeed.php

Total Errors Count: 1

**Comment by magefan** [comment]
Hello @namchinhh ,

Thank you for your report. We have re-tested our extension on Magento 2.3.2 and were not able to reproduce this issue.

1. Make sure that you use the latest extensions versions
1.1. Magefan Login As Customer v2.2.0
1.2. Magefan Community v2.0.6
2. Make sure that you don't have custom modifications in the extension files

You can always download the original archive of [Magento 2 Login As Customer](https://magefan.com/login-as-customer-magento-2-extension) from our website or via the composer. 

Can you tell me please:
1. What PHP version you have
2. What extension versions you use (Magefan Login As Customer, Magefan Community)

**Comment by namchinhh** [comment]
Hi magefan, thanks for your reply. I found that in my project have change
the core module so it makes the error. But its no longer an issue for now
after reinstall core module.

Vào Th 6, 9 thg 8, 2019 lúc 12:38 Magefan <notifications@github.com> đã
viết:
