### ISSUE TITLE
Exception when login and manual store view choose enabled

### ISSUE THREAD

**Issue by angelo983** [magefan/module-login-as-customer#33]
Configuration: Store View To Login In => Manual Choose
Go in Customer List and click on [Magento 2 Login As Customer](https://magefan.com/login-as-customer-magento-2-extension) button
Exception occurs about wrong structure of view\adminhtml\ui_component\manual_store_form.xml

**Comment by magefan** [comment]
@angelo983 , can you please specify what Magento and extension version you use?

**Comment by angelo983** [comment]
magento2 (2.1.18)
magefan/module-login-as-customer (2.2.1)

**Comment by ihorvansach** [comment]
@angelo983 , please use this fix https://github.com/magefan/module-login-as-customer/commit/8893f2ea64f2792ba496208d66ab2f99421f63fe

Let us know if it works well for you.

**Comment by angelo983** [comment]
Sorry for late response, I can confirm that the fix solved the issue. Thank you
