### ISSUE TITLE
Multiple store login not working

### ISSUE THREAD

**Issue by travisdetert** [magefan/module-login-as-customer#37]
Hi,
I've just updated to 2.2.3 and when testing multiple store login I get to the "You're logged in" notification, but then it immediately redirects to login page and I am now logged out.

I've also noticed that I continue to receive the notice upon login that there is an update available, but I can see in the database that the version number is correct.

**Comment by shopwhizzy** [comment]
Same here

**Comment by ihorvansach** [comment]
@travisdetert , @divisum , we have checked this on our test environment and were not able to reproduce the issue. 

Just a suggestion, you can try to enable this option as "Global" https://prnt.sc/rp7yan in the stores configuration > customer. Think that the customer does not have an account on the website.

If it does not help, you can contact us at support@magefan.com and provide access to your stage/dev environment so we can check directly on your server.

**Comment by barryvdh** [comment]
In our case we have multiple websites but can't share the customers. The B2B website is in it's own domain, so the login should take place there.
