### ISSUE TITLE
Compatibility 2.2.9 login.js

### ISSUE THREAD

**Issue by olivermontes** [magefan/module-login-as-customer#38]
Update version 2.2.4 is not Magento 2.2.9 compatibility

![Screen Shot 2020-05-18 at 20 04 47](https://user-images.githubusercontent.com/177077/82245368-1b69d280-9943-11ea-9278-2cad143da122.png)

Working around
- Rollback this line
https://github.com/magefan/module-login-as-customer/commit/406bcdf57fe37be74740cf4ba657b273fa6d1280#diff-318073310f0e9e021b591a2ea9297bbbL13
`customerData.reload('customer').done(function () {`

**Comment by ihorvansach** [comment]
@olivermontes ,

Could you please try this fix https://github.com/magefan/module-login-as-customer/commit/236b215219470b24fd222664ca4607c9e5f387a6

Let me know if it works well for you

**Comment by olivermontes** [comment]
@ihorvansach it's work great, fast fix nice support! 👍 

next release date? 🤔

**Comment by ihorvansach** [comment]
@olivermontes , v2.2.5 has been released.
