### ISSUE TITLE
getting 404 page not found if we login as customer

### ISSUE THREAD

**Issue by dipkumarjoshi** [magefan/module-login-as-customer#39]
Hello There,

If I am trying to login as customer from backend admin then it is leading to 404 page intead of that customer login.

**Comment by magefan** [comment]
Think you use Magento 2.4.2 right? If yes, please check this articles:
https://magefan.com/login-as-customer-magento-2-extension/magento-2.4.x
https://magefan.com/magefan-login-as-customer-extension-now-is-part-of-magento-240-core

**Comment by TuVanDev** [comment]
Just let you know your guide on the article has a typo, so it can't give user disable the module 
[https://magefan.com/magefan-login-as-customer-extension-now-is-part-of-magento-240-core](https://magefan.com/magefan-login-as-customer-extension-now-is-part-of-magento-240-core#:~:text=bin/magento%20module%3Adisable%20Magefan_LoginasCustomer)

bin/magento module:disable Magefan_LoginasCustomer
Should be changed to
bin/magento module:disable Magefan_LoginAsCustomer

**Comment by magefan** [comment]
@Viper9x , thank you for your report. We will fix that ASAP
