### ISSUE TITLE
Login as customer does not Login as Customer's group

### ISSUE THREAD

**Issue by Sam-PUMP** [magefan/module-login-as-customer#4]
For example, if a customer has special cart or price rules that apply when they are logged in and shopping and if an admin user has an account with a different customer group (ie: customer group for employees) logs in as the customer, the admin will not get the same rules apply as the customer they are logged into. Also in some cases, the admin user's group gets attached to the customers quote instead causing incorrect pricing and order treatment for the customer even if the customer logs in afterwards.

In **quote** table, the value for `customer_group_id` is detected as the customer group of the admin user logged in rather then the customer who we are logging in as.  

To solve I would imagine making sure to set the `customer_group_id` on the **quote** table as the customer's rather then the current user would work.

**Comment by erikhansen** [comment]
@magefan Have you ever looked into this issue? We're getting ready to use this extension on a project where it will be important for this functionality to work.

**Comment by magefan** [comment]
@Sam-PUMP, @erikhansen please try to use this fix https://github.com/magefan/module-login-as-customer/commit/cb9f25f662734b931a4e704ea50e6e3d2cc1824e for [Magento 2 Login As Customer Module](https://magefan.com/login-as-customer-magento-2-extension) .

Please let us know if it works.

**Comment by erikhansen** [comment]
@Sam-PUMP I have not spent time to reproduce the issue. Can you reproduce the issue, update your environment to use the updated code, and then see if the issue goes away?
