### ISSUE TITLE
Does not work with Magento 2.1.9

### ISSUE THREAD

**Issue by MattDelac** [magefan/module-login-as-customer#7]
Hello there,

First of all, thank you for your awesome module

Second of all, we just updated from 2.1.6 to 2.1.9 and installed the latest version of this module (through composer).
The module does not work as well ad before.

There was no issue during the installation, nor in the backoffice but when I clic on the "Login As Customer" button (from the "All customers list page", it redirects me to a page with a link that looks like "account/login/referer/aHR0cHM6Ly9kZXYubWVkZWx5cy5mci9jdXN0b21lci9hY2NvdW50L2luZGV4Lw%2C%2C/" but it does not work...

I have the same issue if I am on a client detail page.

Thank you to let me know
Matt

**Comment by magefan** [comment]
@MattDelac we re-tested latest [Login as Customer Extension](https://magefan.com/login-as-customer-magento-2-extension) v2.1.2 on Magento 2.1.9 without any issues. Please
1. Make sure that you are using v2.1.2
2. Try to run these commands
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento setup:static-content:deploy

**Comment by erikhansen** [comment]
I'm using this extension on EE 2.1.9 without issues.
